### ISSUE TITLE
Error in console after successfully run

### ISSUE THREAD

**Issue by dfaruque** [chaegumi/bookmarking-app-electron-vuejs-sqlite#3]
![image](https://user-images.githubusercontent.com/16621563/34774761-cedbbf62-f63a-11e7-8656-1f796f708b43.png)

Please help me to remove these errors.

Thanks.

**Comment by chaegumi** [comment]
https://gist.github.com/maximilian-ruppert/9de273f72c1ba4aa62d6  this article can help you.

**Comment by dfaruque** [comment]
Thank you.
unfortunately this link says 404 

![image](https://user-images.githubusercontent.com/16621563/34808795-5adf6812-f6bb-11e7-9c86-3bd12784a019.png)

**Comment by meddjelaili** [comment]
@chaegumi are you referring to this https://gist.github.com/craigvantonder/f59277cd788f8aa755e3bdbe5d21f08e ?
